name: Repository Dispatch
on:
  repository_dispatch:
    types: [x3dom-release]
jobs:
  publishRelase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: x3dom
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - run: echo ${{ github.event.client_payload.repositoryUrl }}
      - run: echo ${{ github.event.client_payload.ref }}
