name: Repository Dispatch
on:
  repository_dispatch:
    types: [x3dom-released]
jobs:
  checkoutBuildAndUploadRelase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - name: Build release
        run: |
          npm install
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x3dom-dist
          path: dist/
  downloadCommitAndPushRelease:
    runs-on: ubuntu-latest
    needs: checkoutBuildAndUploadRelase
    steps:
      - name: Checkout current head
        uses: actions/checkout@v3
      - name: Check if dist folder exists
        id: check_dist
        uses: andstor/file-existence-action@v2
        with:
          files: "dist"
      - name: Remove entire dist-folder
        if: steps.check_dist.outputs.files_exists == 'true'
        run: git rm -r dist/
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: x3dom-dist
          path: dist/
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/'
          message: github.event.client_payload.tag_name
      - run: echo ${{ github.event.client_payload.repositoryUrl }}
      - run: echo ${{ github.event.client_payload.ref }}
